# Generated by Django 5.2.11 on 2026-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MergeOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("file1_name", models.CharField(max_length=255)),
                ("file2_name", models.CharField(max_length=255)),
                ("merge_key", models.CharField(max_length=255)),
                (
                    "merge_type",
                    models.CharField(
                        choices=[
                            ("inner", "Inner Join"),
                            ("outer", "Outer Join"),
                            ("left", "Left Join"),
                            ("right", "Right Join"),
                        ],
                        default="outer",
                        max_length=20,
                    ),
                ),
                (
                    "duplicate_handling",
                    models.CharField(
                        choices=[
                            ("keep_first", "Keep First"),
                            ("keep_last", "Keep Last"),
                            ("keep_all", "Keep All"),
                        ],
                        default="keep_first",
                        max_length=20,
                    ),
                ),
                ("output_filename", models.CharField(blank=True, max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("file1_rows", models.IntegerField(default=0)),
                ("file2_rows", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Merge Operation",
                "verbose_name_plural": "Merge Operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("rows", models.IntegerField(default=0)),
                ("columns", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
